executable            = merge.sh
requirements          = (OpSysAndVer =?= "CentOS8")
error                 = err/merge-$(ClusterId).$(ProcId).err
output                = out/merge-$(ClusterId).$(ProcId).out
+JobBatchName         = "merge_$(type)_$(LABEL)"
+JobFlavour           = "longlunch"
should_transfer_files = YES

type                  = fullsim
transfer_input_files  = merge.py
arguments             = $(type) $(LABEL) $(vCMSSW) $(BASE)

queue
