executable            = mergeOutputFiles.sh
requirements          = (OpSysAndVer =?= "CentOS7")
error                 = err/$(ClusterId).$(ProcId).err
output                = out/$(ClusterId).$(ProcId).out
log                   = log/$(ClusterId).$(ProcId).log
+JobBatchName         = "merge_full_step3"
+JobFlavour           = "microcentury"
should_transfer_files = YES

transfer_input_files  = copyPickMerge_cfg.py
arguments             = fullsim vtx0

queue
