executable            = step3.sh
requirements          = (OpSysAndVer =?= "CentOS7")
error                 = err/step3/$(ClusterId).$(ProcId).err
output                = out/step3/$(ClusterId).$(ProcId).out
log                   = log/step3/$(ClusterId).$(ProcId).log
+JobBatchName         = "full_step3_$(LABEL)"
+JobFlavour           = "workday"
should_transfer_files = YES

transfer_input_files  = step3.py
arguments             = $(Process) step3.py step3 $(vCMSSW) $(EVTS) $(LABEL)
# 1: seed to be used as InitialSeed
# 2: config file for step1
# 3: job name and output folder in EOS
# 4: cmssw release
# 5: number of events per file
# 6: label for job outputs

queue $(FILES)
